"""Audit ``data/splits/{train,dev,test}.jsonl`` and emit a markdown report.

The report is included as Appendix material in the thesis and as the
provenance for the data-quality findings in Chapter~7. It reproduces six
findings:

  1. Trivial-copy pairs (source == target with empty errors).
  2. Error-type histogram per split.
  3. Errors-per-record distribution (single vs. multi-edit).
  4. Character-normalisation audit (Arabic-YEH/KAF/HEH, BOM, NFC).
  5. Edit-density stats (mean number of edited tokens per active pair).
  6. Cross-split source-string leakage check.

Run from the repository root:

    python -m scripts.diagnose_data

Output: ``results/data_diagnosis/report.md``.
"""

from __future__ import annotations

import json
import logging
import unicodedata
from collections import Counter
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(message)s")
log = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parents[1]
SPLITS = ROOT / "data" / "splits"
OUT = ROOT / "results" / "data_diagnosis"

ARABIC_YEH = "\u064A"
ARABIC_KAF = "\u0643"
ARABIC_HEH = "\u0647"
KURDISH_HEH = "\u06D5"
BOM = "\uFEFF"


def load(p: Path) -> list[dict]:
    return [json.loads(l) for l in p.read_text(encoding="utf-8").splitlines()]


def char_audit(records: list[dict]) -> dict[str, int]:
    text = "\n".join(r["source"] for r in records)
    nfc = sum(1 for r in records if unicodedata.normalize("NFC", r["source"]) != r["source"])
    return {
        "arabic_yeh": text.count(ARABIC_YEH),
        "arabic_kaf": text.count(ARABIC_KAF),
        "arabic_heh": text.count(ARABIC_HEH),
        "kurdish_heh": text.count(KURDISH_HEH),
        "bom": text.count(BOM),
        "non_nfc_records": nfc,
    }


def diagnose_split(name: str, records: list[dict]) -> dict:
    n = len(records)
    trivial = sum(1 for r in records if r["source"] == r["target"])
    active = [r for r in records if r["source"] != r["target"]]

    type_hist = Counter()
    for r in active:
        for e in r.get("errors", []):
            type_hist[e["type"]] += 1

    primary_hist = Counter(
        r["errors"][0]["type"] if r.get("errors") else "no_error" for r in active
    )

    errors_per_record = Counter(len(r.get("errors", [])) for r in active)

    # Edit density: count differing whitespace-token positions.
    densities = []
    for r in active:
        s = r["source"].split()
        t = r["target"].split()
        diffs = sum(1 for a, b in zip(s, t) if a != b) + abs(len(s) - len(t))
        densities.append(diffs)
    mean_density = sum(densities) / len(densities) if densities else 0.0

    return {
        "n_total": n,
        "n_trivial": trivial,
        "trivial_pct": 100 * trivial / n if n else 0.0,
        "n_active": len(active),
        "type_histogram": dict(type_hist.most_common()),
        "primary_type_histogram": dict(primary_hist.most_common()),
        "errors_per_record": dict(sorted(errors_per_record.items())),
        "edit_density_mean": mean_density,
        "char_audit": char_audit(records),
    }


def cross_split_leakage(splits: dict[str, list[dict]]) -> dict:
    train_src = {r["source"] for r in splits["train"]}
    dev_src = {r["source"] for r in splits["dev"]}
    test_src = {r["source"] for r in splits["test"]}
    return {
        "train_dev_overlap": len(train_src & dev_src),
        "train_test_overlap": len(train_src & test_src),
        "dev_test_overlap": len(dev_src & test_src),
    }


def fmt_table(headers: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(headers) + " |"]
    out.append("|" + "|".join(["---"] * len(headers)) + "|")
    for r in rows:
        out.append("| " + " | ".join(r) + " |")
    return "\n".join(out)


def render(reports: dict[str, dict], leakage: dict) -> str:
    lines = ["# Data Diagnosis Report", ""]
    lines.append("Generated by `scripts/diagnose_data.py`.")
    lines.append("")

    lines.append("## 1. Trivial Copy-Pairs")
    rows = [
        [name, str(r["n_total"]), str(r["n_trivial"]), f"{r['trivial_pct']:.1f}%", str(r["n_active"])]
        for name, r in reports.items()
    ]
    lines.append(fmt_table(["Split", "Total", "Trivial", "Trivial %", "Active"], rows))
    lines.append("")

    lines.append("## 2. Primary Error-Type Histogram (active pairs)")
    all_types = sorted({t for r in reports.values() for t in r["primary_type_histogram"]})
    rows = []
    for t in all_types:
        rows.append([t] + [str(reports[name]["primary_type_histogram"].get(t, 0)) for name in reports])
    lines.append(fmt_table(["Type", *reports.keys()], rows))
    lines.append("")

    lines.append("## 3. Errors per Record (active pairs)")
    all_keys = sorted({k for r in reports.values() for k in r["errors_per_record"]})
    rows = []
    for k in all_keys:
        rows.append([str(k)] + [str(reports[name]["errors_per_record"].get(k, 0)) for name in reports])
    lines.append(fmt_table(["#errors", *reports.keys()], rows))
    lines.append("")

    lines.append("## 4. Character-Normalisation Audit")
    rows = []
    keys = ["arabic_yeh", "arabic_kaf", "arabic_heh", "kurdish_heh", "bom", "non_nfc_records"]
    for k in keys:
        rows.append([k] + [str(reports[name]["char_audit"][k]) for name in reports])
    lines.append(fmt_table(["Indicator", *reports.keys()], rows))
    lines.append("")
    lines.append("Arabic-HEH counts above zero are expected: medial/final HEH legitimately occurs in Sorani orthography. The relevant pathology would be Arabic-YEH or Arabic-KAF, both of which are zero.")
    lines.append("")

    lines.append("## 5. Edit Density (active pairs)")
    rows = [
        [name, f"{r['edit_density_mean']:.2f}"]
        for name, r in reports.items()
    ]
    lines.append(fmt_table(["Split", "Mean tokens changed"], rows))
    lines.append("")

    lines.append("## 6. Cross-Split Source-String Leakage")
    rows = [
        ["Train n Dev", str(leakage["train_dev_overlap"])],
        ["Train n Test", str(leakage["train_test_overlap"])],
        ["Dev n Test", str(leakage["dev_test_overlap"])],
    ]
    lines.append(fmt_table(["Pair", "Overlapping source strings"], rows))
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    splits = {name: load(SPLITS / f"{name}.jsonl") for name in ("train", "dev", "test")}
    reports = {name: diagnose_split(name, recs) for name, recs in splits.items()}
    leakage = cross_split_leakage(splits)

    md = render(reports, leakage)
    md_path = OUT / "report.md"
    md_path.write_text(md, encoding="utf-8")

    json_path = OUT / "report.json"
    json_path.write_text(
        json.dumps({"per_split": reports, "leakage": leakage}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    log.info("Wrote %s", md_path)
    log.info("Wrote %s", json_path)


if __name__ == "__main__":
    main()
